name: Download

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build website
        run: ./build.sh
        env: 
          OK_USERNAME: ${{ secrets.OK_USERNAME }}
          OK_PASSWORD: ${{ secrets.OK_PASSWORD }}
          OK_CLIENT_ID: ${{ secrets.OK_CLIENT_ID }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public